/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pro1p1_josueham;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.util.*;

public class Labotify extends javax.swing.JFrame {

    ArrayList<Cancion> canciones = new ArrayList<>();
    int indice = 0;

    public Labotify() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameModificar = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        TxtAlbum = new javax.swing.JTextField();
        TxtArtista = new javax.swing.JTextField();
        TxtAnio = new javax.swing.JFormattedTextField();
        TxtDuracion = new javax.swing.JFormattedTextField();
        BtnGuardarCambios = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnAgregar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnLista = new javax.swing.JButton();
        BtnInfo = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnRegresar = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        jLabel2.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Modificar Canción");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Álbum");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Artista");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Año");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Duración");

        TxtNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        TxtAlbum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        TxtArtista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        TxtAnio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####"))));
        TxtAnio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        TxtDuracion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####"))));
        TxtDuracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        BtnGuardarCambios.setText("Guardar Cambios");
        BtnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarCambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(117, 117, 117))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TxtArtista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                .addComponent(TxtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtAlbum, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnGuardarCambios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TxtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtnGuardarCambios)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FrameModificarLayout = new javax.swing.GroupLayout(FrameModificar.getContentPane());
        FrameModificar.getContentPane().setLayout(FrameModificarLayout);
        FrameModificarLayout.setHorizontalGroup(
            FrameModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FrameModificarLayout.setVerticalGroup(
            FrameModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1p1_josueham/prism.png"))); // NOI18N
        jLabel1.setText("Labotify");

        BtnAgregar.setBackground(new java.awt.Color(153, 153, 153));
        BtnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregar.setText("Agregar");
        BtnAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnAgregarMouseExited(evt);
            }
        });
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        BtnEliminar.setBackground(new java.awt.Color(153, 153, 153));
        BtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEliminar.setText("Eliminar");
        BtnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnEliminarMouseExited(evt);
            }
        });
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnLista.setBackground(new java.awt.Color(153, 153, 153));
        BtnLista.setForeground(new java.awt.Color(255, 255, 255));
        BtnLista.setText("Listar");
        BtnLista.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnLista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnListaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnListaMouseExited(evt);
            }
        });
        BtnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListaActionPerformed(evt);
            }
        });

        BtnInfo.setBackground(new java.awt.Color(153, 153, 153));
        BtnInfo.setForeground(new java.awt.Color(255, 255, 255));
        BtnInfo.setText("Informacion");
        BtnInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnInfoMouseExited(evt);
            }
        });
        BtnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInfoActionPerformed(evt);
            }
        });

        BtnModificar.setBackground(new java.awt.Color(153, 153, 153));
        BtnModificar.setForeground(new java.awt.Color(255, 255, 255));
        BtnModificar.setText("Modificar Cancion");
        BtnModificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnModificarMouseExited(evt);
            }
        });
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });

        BtnRegresar.setBackground(new java.awt.Color(153, 153, 153));
        BtnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegresar.setText("Menu");
        BtnRegresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnRegresarMouseExited(evt);
            }
        });
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(BtnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnAgregar)
                .addGap(18, 18, 18)
                .addComponent(BtnEliminar)
                .addGap(18, 18, 18)
                .addComponent(BtnLista)
                .addGap(18, 18, 18)
                .addComponent(BtnInfo)
                .addGap(18, 18, 18)
                .addComponent(BtnModificar)
                .addGap(18, 18, 18)
                .addComponent(BtnRegresar)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        BtnRegresar.setBackground(Color.black);
        BtnRegresar.setForeground(Color.white);
        Menu regresar = new Menu();
        regresar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        String nombre = JOptionPane.showInputDialog(this, "Ingrese el nombre de la cancion: ");
        String album = JOptionPane.showInputDialog(this, "Ingrese el nombre del album: ");
        String artista = JOptionPane.showInputDialog(this, "Ingrese el nombre del artista: ");
        String StrAnio = JOptionPane.showInputDialog(this, "Ingrese el año de lanzamiento: ");
        int anio = Integer.parseInt(StrAnio);
        String StrDuracion = JOptionPane.showInputDialog(this, "Ingrese la duracion de la cancion en segundos: ");
        int duracion = Integer.parseInt(StrDuracion);

        canciones.add(new Cancion(nombre, album, artista, anio, duracion));
        JOptionPane.showMessageDialog(null, "Cancion agregada exitosamente");
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void BtnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListaActionPerformed
        JOptionPane.showMessageDialog(null, ListarCanciones());
    }//GEN-LAST:event_BtnListaActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        String mensaje = ListarCanciones() + "\nIngrese el indice de la cancion que desea eliminar: ";
        String StrIndice = JOptionPane.showInputDialog(null, mensaje);
        int indice = (Integer.parseInt(StrIndice) - 1);
        if (JOptionPane.YES_OPTION == JOptionPane.showInternalConfirmDialog(null, "Seguro que desea eliminar la cancion: "
                + canciones.get(indice).getNombre()
                + " - " + canciones.get(indice).getArtista())) {
            if (indice >= 0 && indice < canciones.size()) {
                canciones.remove(indice);
                JOptionPane.showMessageDialog(null, "Cancion eliminada exitosamente");
            } else {
                JOptionPane.showMessageDialog(null, "La posicion no esta dentro del rango");
            }//fin else
        } 


    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInfoActionPerformed
        String mensaje = ListarCanciones() + "\nIngrese el indice de la cancion que desea: ";
        String StrIndice = JOptionPane.showInputDialog(null, mensaje);
        int indice = (Integer.parseInt(StrIndice) - 1);
        if (indice >= 0 && indice < canciones.size()) {
            JOptionPane.showMessageDialog(null, canciones.get(indice).toString());
        } else {
            JOptionPane.showMessageDialog(null, "La posicion no esta dentro del rango");
        }//fin else
    }//GEN-LAST:event_BtnInfoActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        String mensaje = ListarCanciones() + "\nIngrese el indice de la cancion que desea: ";
        String StrIndice = JOptionPane.showInputDialog(null, mensaje);
        indice = (Integer.parseInt(StrIndice) - 1);
        if (indice >= 0 && indice < canciones.size()) {
            Cancion selected = canciones.get(indice);
            TxtNombre.setText(selected.getNombre());
            TxtAlbum.setText(selected.getAlbum());
            TxtArtista.setText(selected.getArtista());
            TxtAnio.setText("" + selected.getAnio());
            TxtDuracion.setText("" + selected.getDuracion());
            FrameModificar.setSize(394, 560);
            FrameModificar.setLocationRelativeTo(null);
            FrameModificar.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "La posicion no esta dentro del rango");
        }//fin else


    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarCambiosActionPerformed

        String NueNombre = TxtNombre.getText();
        canciones.get(indice).setNombre(NueNombre);
        String NueAlbum = TxtAlbum.getText();
        canciones.get(indice).setAlbum(NueAlbum);
        String NueArtista = TxtArtista.getText();
        canciones.get(indice).setArtista(NueArtista);
        int NueAnio = Integer.parseInt(TxtAnio.getText());
        canciones.get(indice).setAnio(NueAnio);
        int NueDuracion = Integer.parseInt(TxtDuracion.getText());
        canciones.get(indice).setDuracion(NueDuracion);

        BtnGuardarCambios.setBackground(Color.red);
        BtnGuardarCambios.setForeground(Color.white);
        JOptionPane.showMessageDialog(null, "Cambios realizados con exito");
        FrameModificar.dispose();
    }//GEN-LAST:event_BtnGuardarCambiosActionPerformed

    private void BtnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregarMouseEntered
        BtnAgregar.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_BtnAgregarMouseEntered

    private void BtnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarMouseEntered
        BtnEliminar.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_BtnEliminarMouseEntered

    private void BtnListaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnListaMouseEntered
        BtnLista.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_BtnListaMouseEntered

    private void BtnInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnInfoMouseEntered
        BtnInfo.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_BtnInfoMouseEntered

    private void BtnModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnModificarMouseEntered
        BtnModificar.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_BtnModificarMouseEntered

    private void BtnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegresarMouseEntered
        BtnRegresar.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_BtnRegresarMouseEntered

    private void BtnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAgregarMouseExited
        BtnAgregar.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_BtnAgregarMouseExited

    private void BtnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarMouseExited
        BtnEliminar.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_BtnEliminarMouseExited

    private void BtnListaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnListaMouseExited
        BtnLista.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_BtnListaMouseExited

    private void BtnInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnInfoMouseExited
        BtnInfo.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_BtnInfoMouseExited

    private void BtnModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnModificarMouseExited
        BtnModificar.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_BtnModificarMouseExited

    private void BtnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegresarMouseExited
        BtnRegresar.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_BtnRegresarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Labotify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Labotify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Labotify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Labotify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Labotify().setVisible(true);
            }
        });
    }

    public String ListarCanciones() {
        String lista = "";
        for (int i = 1; i <= canciones.size(); i++) {
            lista += i + ". " + canciones.get(i - 1).getNombre() + " - " + canciones.get(i - 1).getArtista() + "\n";
        }
        return lista;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardarCambios;
    private javax.swing.JButton BtnInfo;
    private javax.swing.JButton BtnLista;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JFrame FrameModificar;
    private javax.swing.JTextField TxtAlbum;
    private javax.swing.JFormattedTextField TxtAnio;
    private javax.swing.JTextField TxtArtista;
    private javax.swing.JFormattedTextField TxtDuracion;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
